apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
spec:
  selector:
    matchLabels:
      app: 
  replicas: 1 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: nginx:1.14.2
        ports:
        - containerPort: 80