# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whereami.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewhereami.proto\x12\x08whereami\"\x07\n\x05\x45mpty\"\x9e\x02\n\rWhereamiReply\x12/\n\x0e\x62\x61\x63kend_result\x18\x01 \x01(\x0b\x32\x17.whereami.WhereamiReply\x12\x14\n\x0c\x63luster_name\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12\x11\n\tnode_name\x18\x04 \x01(\t\x12\x0e\n\x06pod_ip\x18\x05 \x01(\t\x12\x10\n\x08pod_name\x18\x06 \x01(\t\x12\x16\n\x0epod_name_emoji\x18\x07 \x01(\t\x12\x15\n\rpod_namespace\x18\x08 \x01(\t\x12\x1b\n\x13pod_service_account\x18\t \x01(\t\x12\x12\n\nproject_id\x18\n \x01(\t\x12\x11\n\ttimestamp\x18\x0b \x01(\t\x12\x0c\n\x04zone\x18\x0c \x01(\t2D\n\x08Whereami\x12\x38\n\nGetPayload\x12\x0f.whereami.Empty\x1a\x17.whereami.WhereamiReply\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_WHEREAMIREPLY = DESCRIPTOR.message_types_by_name['WhereamiReply']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'whereami_pb2'
  # @@protoc_insertion_point(class_scope:whereami.Empty)
  })
_sym_db.RegisterMessage(Empty)

WhereamiReply = _reflection.GeneratedProtocolMessageType('WhereamiReply', (_message.Message,), {
  'DESCRIPTOR' : _WHEREAMIREPLY,
  '__module__' : 'whereami_pb2'
  # @@protoc_insertion_point(class_scope:whereami.WhereamiReply)
  })
_sym_db.RegisterMessage(WhereamiReply)

_WHEREAMI = DESCRIPTOR.services_by_name['Whereami']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=28
  _EMPTY._serialized_end=35
  _WHEREAMIREPLY._serialized_start=38
  _WHEREAMIREPLY._serialized_end=324
  _WHEREAMI._serialized_start=326
  _WHEREAMI._serialized_end=394
# @@protoc_insertion_point(module_scope)
