# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import whereami_pb2 as whereami__pb2


class WhereamiStub(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPayload = channel.unary_unary(
                '/whereami.Whereami/GetPayload',
                request_serializer=whereami__pb2.Empty.SerializeToString,
                response_deserializer=whereami__pb2.WhereamiReply.FromString,
                )


class WhereamiServicer(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    def GetPayload(self, request, context):
        """Send host name and get other metadata back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhereamiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayload,
                    request_deserializer=whereami__pb2.Empty.FromString,
                    response_serializer=whereami__pb2.WhereamiReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whereami.Whereami', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Whereami(object):
    """import "google/protobuf/struct.proto";

    The whereami service definition.
    """

    @staticmethod
    def GetPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/whereami.Whereami/GetPayload',
            whereami__pb2.Empty.SerializeToString,
            whereami__pb2.WhereamiReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
