apiVersion: v1
kind: Service
metadata:
  name: recommendations
  labels:
    app: recommendations
spec:
  type: ClusterIP
  selector:
    app: recommendations
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080