apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: checkout-virtualservice
    namespace: checkout
spec:
    hosts:
    - checkout.checkout.cluster.local.svc
    gateways:
    - asm-ingress-gw/asm-ingressgateway
    http:
    - route:
      - destination:
          host: checkout
          port:
            number: 80
