apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: asm-ingressgateway-http-xlb
  namespace: gateways
spec:
  gatewayClassName: gke-l7-global-external-managed-mc
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
 
