# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable

timeout: 7200s # 2hr
tags:
  - app-shop-cart-spanner-db
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
steps:
# Create Spanner database for Cart items
# DEPLOYMENT_STRATEGY var is defined in vars.sh file in the root folder
- name: gcr.io/cloud-builders/gcloud
  id: '00-shop-cart-spanner-db'
  dir: spanner
  entrypoint: bash
  args: 
    - -c
    - |
      gsutil cp -r gs://${_PROJECT_ID}/vars.sh infra-vars.sh
      cat infra-vars.sh
      source infra-vars.sh
      source vars.sh
      git config --global user.email "cloudbuild-ci@cloudbuild.gserviceaccount.com"
      git config --global user.name "cloudbuild-ci"
      sed -e "s/SPANNER_NAME/$${SPANNER_NAME}/" database-cart.yaml_tmpl > database-cart.yaml
      gcloud source repos clone infrastructure --project=${_PROJECT_ID}
      mkdir -p infrastructure/databases
      cp -r database-cart.yaml infrastructure/databases
      cat infrastructure/databases/database-cart.yaml
      cd infrastructure
      git add . && git commit -am "Create Cart items DB in Spanner"
      git push
