apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats
spec:
  template:
    spec:
      containers:
          - name: pop-stats
            env:
              - name: SITE_NAME
                value: "Population Stats Staging"