apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: allow-all-10
  namespace: config-control
spec:
  allow:
  - protocol: all
  sourceRanges:
  - "10.0.0.0/8"
  networkRef:
    external: default
