apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: checkout-workload
namespace: checkout
commonLabels:
  app: checkout
resources:
- ../../base
- deployment.yaml
- service.yaml
patches:
- path: deployment.yaml
  target:
    kind: deployment
- path: service.yaml
  target:
    kind: Service
images:
- name: checkoutservice
  newName: us-central1-docker.pkg.dev/arch001/shop-checkout/service
  newTag: latest
