apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: checkout-workload
namePrefix: "checkout"
namespace: checkout
commonLabels:
  app: checkout
resources:
  - ../../base
patches:
