apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: checkout-workload
namespace: checkout
commonLabels:
  app: checkout
resources:
- ../../base
- deployment.yaml
- service.yaml
images:
- name: checkoutservice
  newName: us-central1-docker.pkg.dev/<project-id>/shop-checkout/service
  newTag: latest
