apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cart
build:
  artifacts:
    - image: cart
      context: src
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: deployment
    resourceName: cart
    port: 7070
    localPort: 7070
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
