apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: currency-workload
namespace: currency
commonLabels:
  app: currency
resources:
- ../../base
- deployment.yaml
- service.yaml
images:
- name: currencyservice
  newName: us-central1-docker.pkg.dev/<project-id>/shop-currency/service
  newTag: latest