apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: currency-workload
namePrefix: "currency"
namespace: currency
commonLabels:
  app: currency
resources:
  - ../../base
patches:
