---
apiVersion: v1
kind: Service
metadata:
  name: currency
  labels:
    app: currency
spec:
  type: ClusterIP
  selector:
    app: currency
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000