apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: asm-ingressgateway
  namespace: asm-ingress
  annotations:
    configsync.gke.io/cluster-name-selector: prod-us-central1-0, prod-us-central1-1, prod-us-central1-2, prod-us-west2-0, prod-us-west2-1, prod-us-west2-2
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asm-ingressgateway
  namespace: asm-ingress
  annotations:
    configsync.gke.io/cluster-name-selector: prod-us-central1-0, prod-us-central1-1, prod-us-central1-2, prod-us-west2-0, prod-us-west2-1, prod-us-west2-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: asm-ingressgateway
subjects:
  - kind: ServiceAccount
    name: asm-ingressgateway
