apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: default-httproute
  namespace: asm-ingress-gw
  # annotations:
  #   configsync.gke.io/cluster-name-selector: prod-us-central1-0, prod-us-central1-1, prod-us-central1-2, prod-us-west2-0, prod-us-west2-1, prod-us-west2-2
spec:
  parentRefs:
  - name: external-http
    namespace: asm-ingress-gw
    sectionName: http
  rules:
  - backendRefs:
    - group: net.gke.io
      kind: ServiceImport
      name: asm-ingressgateway
      port: 80