apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shop-productcatalog-dev
spec:
  hosts:
  - shop-productcatalog
  http:
  - match:
    - sourceLabels:
        app: shop-productcatalog
        env: dev
    route:
    - destination:
        host: shop-productcatalog
        subset: shop-productcatalog-dev