apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: payment-workload
namespace: payment
commonLabels:
  app: payment
resources:
- ../../base
- deployment.yaml
- service.yaml
images:
- name: paymentservice
  newName: us-central1-docker.pkg.dev/<project-id>/shop-payment/service
  newTag: latest
