apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: payment-virtualservice
    namespace: payment
spec:
    hosts:
    - payment.payment.svc.cluster.local
    gateways:
    - asm-ingress-gw/asm-ingressgateway
    http:
    - route:
      - destination:
          host: payment
          port:
            number: 50051
