apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: frontend-virtualservice
    namespace: frontend
spec:
    hosts:
    - "shop-frontend.endpoints.arch001.cloud.goog"
    - "shop-frontend.endpoints.smig-rad-001.cloud.goog"

    gateways:
    - asm-ingress-gw/asm-ingressgateway
    http:
    - route:
      - destination:
          host: frontend
          port:
            number: 80
