apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: checkout
build:
  artifacts:
    - image: checkout
      context: src
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: deployment
    resourceName: checkout
    port: 5050
    localPort: 5050
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
