apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: email-workload
namespace: email
commonLabels:
  app: email
resources:
- ../../base
- deployment.yaml
- service.yaml
patches:
- path: deployment.yaml
  target:
    kind: deployment
- path: service.yaml
  target:
    kind: Service
images:
- name: emailservice
  newName: us-central1-docker.pkg.dev/arch001/shop-email/service
  newTag: latest