apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: shipping
build:
  artifacts:
    - image: shipping
      context: src
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: deployment
    resourceName: shipping
    port: 50051
    localPort: 50051
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
