nameSuffix: "-backend"
namespace: "whereami-backend"
commonLabels:
  app: whereami-backend
  env: prod
  org: whereami
bases:
- ../../base
- destrule.yaml
- virtualservice.yaml
patches:
  - path: cm-flag.yaml
  - path: service-type.yaml
