# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2hr
tags:
  - infra-acm-selectors-policies-whereami-test-app
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
steps:
# ASM install whereami
# Docs:
# 1. Whereami Github repo -> https://github.com/theemadnes/gke-whereami
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-app-cluster-resources"
  dir: "acm"
  entrypoint: bash
  args:
    - -c
    - |
      source ../infra/vars.sh
      mkdir -p /workspace/clusterregistry
      sed -e "s/CLUSTER_NAME/$${GKE_PROD1_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_1}/" -e "s/ZONE/$${GKE_PROD1_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD1_NAME}.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD2_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_1}/" -e "s/ZONE/$${GKE_PROD2_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD2_NAME}.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD3_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_1}/" -e "s/ZONE/$${GKE_PROD3_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD3_NAME}.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD4_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_2}/" -e "s/ZONE/$${GKE_PROD4_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD4_NAME}.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD5_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_2}/" -e "s/ZONE/$${GKE_PROD5_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD5_NAME}.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD6_NAME}/" -e "s/ENV/prod/" -e "s/REGION/$${GKE_PROD_REGION_2}/" -e "s/ZONE/$${GKE_PROD6_LOCATION}/" -e "s/TYPE/apps/" -e "s/INFRA/gcp/" clusterregistry/cluster.yaml > /workspace/clusterregistry/cluster-$${GKE_PROD6_NAME}.yaml
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-app-clusterselector-resources-prod"
  dir: "acm"
  entrypoint: bash
  args:
    - -c
    - |
      source ../infra/vars.sh
      mkdir -p /workspace/clusterregistry
      sed -e "s/NAME/apz-p-r1-ab/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD1_LOCATION}\n      - $${GKE_PROD2_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r1-ab.yaml
      sed -e "s/NAME/apz-p-r1-ac/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD1_LOCATION}\n      - $${GKE_PROD3_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r1-ac.yaml
      sed -e "s/NAME/apz-p-r1-bc/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD2_LOCATION}\n      - $${GKE_PROD3_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r1-bc.yaml
      sed -e "s/NAME/apz-p-r2-ab/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD4_LOCATION}\n      - $${GKE_PROD5_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r2-ab.yaml
      sed -e "s/NAME/apz-p-r2-ac/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD4_LOCATION}\n      - $${GKE_PROD6_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r2-ac.yaml
      sed -e "s/NAME/apz-p-r2-bc/" -e \
        "s/MATCH/    matchExpressions:\n    - key: zone\n      operator: In\n      values:\n      - $${GKE_PROD5_LOCATION}\n      - $${GKE_PROD6_LOCATION}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apz-p-r2-bc.yaml
      sed -e "s/NAME/mz-p-r1/" -e \
        "s/MATCH/    matchExpressions:\n    - key: region\n      operator: In\n      values:\n      - $${GKE_PROD_REGION_1}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-mz-p-r1.yaml
      sed -e "s/NAME/mz-p-r2/" -e \
        "s/MATCH/    matchExpressions:\n    - key: region\n      operator: In\n      values:\n      - $${GKE_PROD_REGION_2}\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-mz-p-r2.yaml
      sed -e "s/NAME/apr-p/" -e \
        "s/MATCH/    matchExpressions:\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-apr-p.yaml
      sed -e "s/NAME/ir-p/" -e \
        "s/MATCH/    matchExpressions:\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-ir-p.yaml
      sed -e "s/NAME/g-p/" -e \
        "s/MATCH/    matchExpressions:\n    - key: env\n      operator: In\n      values:\n      - prod/" \
         clusterregistry/clusterselector.yaml > /workspace/clusterregistry/clusterselector-g-p.yaml
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-app-whereami-acm"
  dir: "acm"
  entrypoint: bash
  args:
    - -c
    - |
      source ../infra/vars.sh
      git config --global user.email "cloudbuild-ci@cloudbuild.gserviceaccount.com"
      git config --global user.name "cloudbuild-ci"
      gcloud source repos clone config --project=${_PROJECT_ID}
      cp -r /workspace/clusterregistry config/
      cp -r prod config/
      cd config
      git add . && git commit -am "Deploy Clusters, ClusterSelectors, Mesh policy bundle and whereami app to prod env"
      git push

#      cp -r policies config/
