# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 7200s # 2hr
tags:
  - infra-gke-config-fleet-reg
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
steps:
# Register GKE config clusters to Fleet
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-gke-config-fleet-reg"
  dir: "infra"
  entrypoint: bash
  args:
    - -c
    - |
      source vars.sh
      export CONFIG_REGISTERED=$(gcloud --project=${_PROJECT_ID} container fleet memberships list --filter="name:$${GKE_CONFIG_NAME}")
      echo -e "CONFIG_REGISTERED is $$CONFIG_REGISTERED"
      if [[ ! $${CONFIG_REGISTERED} ]]; then
        while [[ $(gcloud container clusters describe $${GKE_CONFIG_NAME} --zone $${GKE_CONFIG_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
          echo "Waiting for $${GKE_CONFIG_NAME} cluster to be RUNNING."
          sleep 5
        done
        gcloud container fleet memberships register $${GKE_CONFIG_NAME} \
          --gke-cluster $${GKE_CONFIG_LOCATION}/$${GKE_CONFIG_NAME} \
          --enable-workload-identity \
          --project=${_PROJECT_ID}
      fi
