# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Notes: Sept 13th 2022: Due to the following error, I am choosing to use the manual install method:
# ERROR: (gcloud.beta.container.hub.config-management.apply) ABORTED: unable to queue the operation
# The docs for manual install at: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl

timeout: 7200s # 2hr
tags:
  - infra-features-gke-prod-acm
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
steps:
# Install ACM ConfigSync GKE Prod1
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod1-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod1.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD1_NAME} --zone $${GKE_PROD1_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD1_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod1-acm-konfig && export KUBECONFIG=gke-prod1-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD1_NAME} --zone $${GKE_PROD1_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod1-acm-konfig apply -f config-management-operator-prod1.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD1_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod1.yaml
      kubectl --kubeconfig=gke-prod1-acm-konfig apply -f acm/config-management-prod1.yaml
      until kubectl --kubeconfig=gke-prod1-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod1-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod1-acm-konfig apply -f acm/root-sync.yaml
# - name: "gcr.io/cloud-builders/gcloud"
#   id: "infra-features-gke-prod1-acm-using-hub-api"
#   dir: "infra"
#   entrypoint: bash
#   args:
#     - -c
#     - |
#       source vars.sh
#       sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/apply-spec.yaml_tmpl > acm/apply-spec.yaml
#       gcloud beta container hub config-management apply \
#         --membership=$${GKE_PROD1_NAME} \
#         --config=acm/apply-spec.yaml \
#         --project=${_PROJECT_ID}
# Install ACM ConfigSync GKE Prod2
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod2-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod2.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD2_NAME} --zone $${GKE_PROD2_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD2_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod2-acm-konfig && export KUBECONFIG=gke-prod2-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD2_NAME} --zone $${GKE_PROD2_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod2-acm-konfig apply -f config-management-operator-prod2.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD2_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod2.yaml
      kubectl --kubeconfig=gke-prod2-acm-konfig apply -f acm/config-management-prod2.yaml
      until kubectl --kubeconfig=gke-prod2-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod2-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod2-acm-konfig apply -f acm/root-sync.yaml
# Install ACM ConfigSync GKE Prod3
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod3-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod3.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD3_NAME} --zone $${GKE_PROD3_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD3_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod3-acm-konfig && export KUBECONFIG=gke-prod3-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD3_NAME} --zone $${GKE_PROD3_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod3-acm-konfig apply -f config-management-operator-prod3.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD3_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod3.yaml
      kubectl --kubeconfig=gke-prod3-acm-konfig apply -f acm/config-management-prod3.yaml
      until kubectl --kubeconfig=gke-prod3-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod3-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod3-acm-konfig apply -f acm/root-sync.yaml
# Install ACM ConfigSync GKE Prod4
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod4-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod4.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD4_NAME} --zone $${GKE_PROD4_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD4_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod4-acm-konfig && export KUBECONFIG=gke-prod4-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD4_NAME} --zone $${GKE_PROD4_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod4-acm-konfig apply -f config-management-operator-prod4.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD4_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod4.yaml
      kubectl --kubeconfig=gke-prod4-acm-konfig apply -f acm/config-management-prod4.yaml
      until kubectl --kubeconfig=gke-prod4-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod4-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod4-acm-konfig apply -f acm/root-sync.yaml
# Install ACM ConfigSync GKE Prod5
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod5-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod5.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD5_NAME} --zone $${GKE_PROD5_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD5_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod5-acm-konfig && export KUBECONFIG=gke-prod5-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD5_NAME} --zone $${GKE_PROD5_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod5-acm-konfig apply -f config-management-operator-prod5.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD5_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod5.yaml
      kubectl --kubeconfig=gke-prod5-acm-konfig apply -f acm/config-management-prod5.yaml
      until kubectl --kubeconfig=gke-prod5-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod5-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod5-acm-konfig apply -f acm/root-sync.yaml
# Install ACM ConfigSync GKE Prod6
# Docs:
# 1. Install Config Sync -> https://cloud.google.com/anthos-config-management/docs/how-to/installing-config-sync#google-service-account
# 2. Manual install Config Sync: https://cloud.google.com/anthos-config-management/docs/how-to/installing-kubectl
- name: "gcr.io/cloud-builders/gcloud"
  id: "infra-features-gke-prod6-acm"
  dir: "infra"
  entrypoint: bash
  waitFor: ['-']
  args:
    - -c
    - |
      source vars.sh
      gsutil cp gs://config-management-release/released/latest/config-management-operator.yaml config-management-operator-prod6.yaml
      while [[ $(gcloud container clusters describe $${GKE_PROD6_NAME} --zone $${GKE_PROD6_LOCATION} --project ${_PROJECT_ID} --format="value(status)") != "RUNNING" ]]; do
        echo "Waiting for $${GKE_PROD6_NAME} cluster to be RUNNING."
        sleep 5
      done
      touch gke-prod6-acm-konfig && export KUBECONFIG=gke-prod6-acm-konfig && \
      gcloud container clusters get-credentials $${GKE_PROD6_NAME} --zone $${GKE_PROD6_LOCATION} --project ${_PROJECT_ID}
      kubectl --kubeconfig=gke-prod6-acm-konfig apply -f config-management-operator-prod6.yaml
      sed -e "s/CLUSTER_NAME/$${GKE_PROD6_NAME}/" acm/config-management-cluster.yaml > acm/config-management-prod6.yaml
      kubectl --kubeconfig=gke-prod6-acm-konfig apply -f acm/config-management-prod6.yaml
      until kubectl --kubeconfig=gke-prod6-acm-konfig get customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io; do date; sleep 1; echo ""; done
      kubectl --kubeconfig=gke-prod6-acm-konfig wait --for=condition=established customresourcedefinitions rootsyncs.configsync.gke.io reposyncs.configsync.gke.io --timeout 5m
      sed -e 's/PROJECT_ID/${_PROJECT_ID}/' acm/root-sync.yaml_tmpl > acm/root-sync.yaml
      kubectl --kubeconfig=gke-prod6-acm-konfig apply -f acm/root-sync.yaml
