apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: productcatalog
build:
  artifacts:
    - image: productcatalog
      context: src
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: deployment
    resourceName: productcatalog
    port: 3550
    localPort: 3550
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
