apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: whereami-backend-workload
nameSuffix: "-backend"
namespace: whereami-backend
commonLabels:
  app: whereami-backend
resources:
  - github.com/GoogleCloudPlatform/kubernetes-engine-samples/quickstarts/whereami/k8s
  - ../../base
patches:
- path: cm-flag.yaml
  target:
    kind: ConfigMap
- path: service-type.yaml
  target:
    kind: Service