nameSuffix: "-backend"
namespace: "whereami-backend"
commonLabels:
  app: whereami-backend
  env: dev
  org: whereami
bases:
- ../../base
- destrule.yaml
- virtualservice.yaml
patches:
- cm-flag.yaml
- service-type.yaml
