apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ad-workload
namespace: ad
commonLabels:
  app: ad
resources:
- ../../base
- deployment.yaml
patches:
- path: deployment.yaml
  target:
    kind: deployment
- path: service.yaml
  target:
    kind: Service
images:
- name: adservice
  newName: us-central1-docker.pkg.dev/arch001/shop-ad/service
  newTag: latest
