apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: productcatalog-workload
namePrefix: "productcatalog"
namespace: productcatalog
commonLabels:
  app: productcatalog
resources:
  - ../../base
patches:
