apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: redis
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: deployment
    resourceName: redis
    port: 6379
    localPort: 6379
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
