# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
kind: SourceRepoRepository
metadata:
  name: bank
  namespace: config-control
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-accounts-db-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "accounts-db/**"
  filename: "accounts-db/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-balancereader-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "balancereader/**"
  filename: "balancereader/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-contacts-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "contacts/**"
  filename: "contacts/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-frontend-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "frontend/**"
  filename: "frontend/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-ledger-db-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "ledger-db/**"
  filename: "ledger-db/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-ledgerwriter-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "ledgerwriter/**"
  filename: "ledgerwriter/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-loadgenerator-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "loadgenerator/**"
  filename: "loadgenerator/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-transactionhistory-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "transactionhistory/**"
  filename: "transactionhistory/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-user-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "user/**"
  filename: "user/ci.yaml"