apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
kind: SourceRepoRepository
metadata:
  name: bank
  namespace: config-control
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-accounts-db-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "accounts-db/**"
  filename: "accounts-db/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-balancereader-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "balancereader/**"
  filename: "balancereader/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-contacts-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "contacts/**"
  filename: "contacts/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-frontend-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "frontend/**"
  filename: "frontend/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-ledger-db-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "ledger-db/**"
  filename: "ledger-db/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-ledgerwriter-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "ledgerwriter/**"
  filename: "ledgerwriter/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-loadgenerator-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "loadgenerator/**"
  filename: "loadgenerator/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-transactionhistory-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "transactionhistory/**"
  filename: "transactionhistory/ci.yaml"
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: bank-user-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: bank
    branchName: main
  includedFiles:
    - "user/**"
  filename: "user/ci.yaml"