apiVersion: sourcerepo.cnrm.cloud.google.com/v1beta1
kind: SourceRepoRepository
metadata:
  name: ops
  namespace: config-control
---
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: ops-asm-trigger
  namespace: config-control
spec:
  disabled: false
  triggerTemplate:
    repoRef:
      name: ops
    branchName: main
  includedFiles:
    - "asm/**"
  filename: "asm/ci.yaml"
