apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: accounts-db
build:
  artifacts:
    - image: accounts-db
      context: src
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: statefulset
    resourceName: accounts-db
    port: 5432
    localPort: 5432
profiles:
  - name: non-prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/non-prod
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
