name: TF checks
on:
  pull_request:
    branches:
      - main
jobs:
  tf-format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: hashicorp/setup-terraform@v3
      - run: go install github.com/terraform-docs/terraform-docs@v0.18.0
      - run: make lint
      - name: diff check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Lint checks modified the following files. Run `make lint` to resolve."
            git status
            exit 1
          fi

