name: TF checks
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt --check --recursive
